config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get 'validate/:validation_token', to: 'users#validate', as: :validate
  resources :users, only: [:index, :new, :create]
  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:index, :create]
  resource :session, only: [:create, :destroy]

end

app/models/logical_state.rb
LogicalState = Struct.new(:state)

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :relationships
  has_many :followers, through: :relationships
  has_many :inverse_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followings, through: :inverse_relationships, source: :user
  has_many :relevant_posts, through: :followings, source: :posts

  def following?(user)
    followings.include? user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  protected

  def current_user
    return @current_user unless session[:user_id].present?
    @current_user ||= if current_user_machine.find! current_user_params
      current_user_params[:user]
    end
  end

  def authenticate!
    redirect_to new_user_path unless current_user.present?
  end

  def current_user_params
    @current_user_params ||= {
      user_id: session[:user_id]
    }
  end

  def current_user_machine
    UserLocation.new(LogicalState.new)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate!

  def index
    machine = PostList.new(LogicalState.new)
    list_params = { user_id: current_user.id }
    if machine.list! list_params
      @posts = list_params[:posts]
    else
      @posts = []
    end
    @post = Post.new
  end

  def create
    machine = PostCreation.new(LogicalState.new)
    if machine.create_post!(post_params) || machine.create_reply!(post_params)
      redirect_to root_path, notice: 'Drivel added.'
    else
      redirect_to root_path, alert: machine.failure_messages.join(', ')
    end
  end

  private

  def post_params
    {
      user_id: current_user.id,
      message: params[:post][:message]
    }
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate!

  def create
    machine = UserFollow.new(LogicalState.new)
    if machine.follow! follow_params
      redirect_to users_path, notice: 'Follow successful.'
    else
      redirect_to users_path, alert: machine.failure_messages.join(', ')
    end
  end

  def destroy
    machine = UserUnfollow.new(LogicalState.new)
    if machine.unfollow! unfollow_params
      redirect_to users_path, notice: 'You have stopped following.'
    else
      redirect_to users_path, alert: machine.failure_messages.join(', ')
    end
  end

  private
  def follow_params
    {
      user_id: params[:relationship][:user_id],
      follower_id: current_user.id
    }
  end

  def unfollow_params
    {
      user_id: params[:id],
      follower_id: current_user.id
    }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate!, except: [:create]

  def create
    machine = SessionCreation.new(LogicalState.new)
    if machine.create! user_params
      redirect_to root_path, notice: 'Welcome back.'
    else
      redirect_to root_path, alert: machine.failure_messages.join(', ')
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_user_path, notice: 'Signed out.'
  end

  private

  def user_params
    {
      email: params[:user][:email],
      password: params[:user][:password],
      session: session
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate!, except: [:new, :create, :validate]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    machine = UserCreation.new(LogicalState.new)
    if machine.create! user_params
      redirect_to root_path, notice: 'Welcome to Twitly'
    else
      render :new
    end
  end

  def validate
    machine = UserValidation.new(LogicalState.new)
    if machine.validate! validation_params
      redirect_to root_path, notice: 'Thank you for validating'
    else
      redirect_to root_path, alert: 'We could not validate your account'
    end
  end

  private

  def user_params
    {
      email: params[:user][:email],
      handle: params[:user][:handle],
      password: params[:user][:password],
      session: session
    }
  end

  def validation_params
    {
      validation_token: params[:validation_token],
      session: session
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message_class(name)
    return 'danger' if name == 'alert'
    return 'success' if name == 'notice'
    return 'info'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title MicroBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    == render 'shared/header'
    == render 'shared/flash_messages'
    .container
      = yield

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message
  = f.input :message, as: :text
  = f.button :submit, 'Post'

app/views/posts/_post.html.slim
.post.panel.panel-default
  .panel-body
    p = post.message
  .panel-footer.by_line
    | - &nbsp;
    = post.user.handle

app/views/posts/index.html.slim
.row
  .col-md-3
    == render 'form'
  .col-md-9
    = render @posts

app/views/shared/_flash_messages.html.slim
- flash.each do |name, msg|
  div class=("alert alert-#{flash_message_class(name)}")
    button.close aria-hidden="true" data-dismiss="alert" type="button"  &times;
    = content_tag :div, msg.html_safe, :id => "flash_#{name}"

app/views/shared/_header.html.slim
nav.navbar.navbar-default role='navigation'
  .container-fluid
    .navbar-header
      button.navbar-toggle type='button' data-toggle='collapse' data-target='#collapsed-navbar'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href='/' Twittly
    #collapsed-navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to 'Users', users_path
      -if current_user.present?
        ul.nav.navbar-nav.navbar-right
          li= link_to 'Sign Out', session_path, method: :delete

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  = f.input :email
  = f.input :handle
  = f.input :password
  = f.button :submit, 'Sign Up'

app/views/users/_sign_in_form.html.slim
= simple_form_for @user, url: { controller: "sessions", action: "create" } do |f|
  = f.input :email
  = f.input :password
  = f.button :submit, 'Sign In'

app/views/users/_user.html.slim
.user.well
  .row
    .col-md-6
      = user.handle
    .col-md-6
      - if current_user.following? user
        = link_to 'Unfollow', relationship_path(user.id), method: :delete, class: 'btn btn-danger'
      -else
        = simple_form_for Relationship.new(user_id: user.id) do |f|
          = f.input :user_id, as: :hidden
          = f.button :submit, 'Follow', class: 'btn-success'

app/views/users/index.html.slim
.row
  .col-md-12
    = render @users

app/views/users/new.html.slim
.row
  .col-md-6
    h2 New user
    == render 'form'
  .col-md-6
    h2 Returning
    == render 'sign_in_form'